apar_technologies_dhl_api.settings:
  type: config_object
  label: 'Apar Technologies DHL API settings'
  mapping:
    api_base_url:
      type: string
      label: 'API Base URL'
    api_key:
      type: string
      label: 'API Key'
